[build-system]
name = "balance"
requires = ["setuptools>=61.0"] # Specifies the build tool (setuptools)
build-backend = "setuptools.build_meta"
[tool.setuptools.packages.find]
include = ["balance"]

[project]
name = "balance" # Choose a name for your project
version = "0.1.0" # Initial version
description = "A project for simulating balance with MuJoCo." # Optional description
readme = "README.md" # Optional: if you have a README
requires-python = ">=3.8" # Specify compatible Python versions
dependencies = [
    "mujoco==3.3.2",
    "numpy<2.0,>=1.23.5",
    "scipy",
    "tyro==0.9.19",
    "tensorflow==2.14",
    "tf-agents==0.19.0",
    # Add other direct dependencies here as needed
]
